//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rewind.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string comments { get; set; }
        public System.DateTime date { get; set; }
        public int feedbackid { get; set; }
    
        public virtual FileUploader FileUploader { get; set; }
        public virtual Feedback Feedback1 { get; set; }
        public virtual Feedback Feedback2 { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
