//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rewind.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImageBrowserEntities : DbContext
    {
        public ImageBrowserEntities()
            : base("name=ImageBrowserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileUploader> FileUploaders { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }

        public System.Data.Entity.DbSet<Rewind.Models.ViewModel.RegistrationViewModel> RegistrationViewModels { get; set; }

        public System.Data.Entity.DbSet<Rewind.Models.ViewModel.FeedbackViewModel> FeedbackViewModels { get; set; }

        public System.Data.Entity.DbSet<Rewind.Models.ViewModel.FileUploadViewModel> FileUploadViewModels { get; set; }
    }
}
